### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by jpobeda** [artyomovs/netbox-plugin-config-officer#2]
Hi there,

I watched your youtube video and decided to give it a go. It looks very neat. Good work :)

I found a few things. I don't run netbox-docker so I went the pip install way

<details><summary>1) There is an import that doesn't look right on `config_officer/views.py`</summary>

```
from netbox.views.generic import (
    ObjectListView, 
    ObjectEditView, 
    BulkDeleteView,
    ObjectDeleteView
)
```

Shouldn't this be?

```
from utilities.views import (
    ObjectListView, 
    ObjectEditView, 
    BulkDeleteView,
    ObjectDeleteView
)
```
</details>

<details><summary>2) The other issue is the migrations file, it has a dependency that can't be met</summary>

```
django.db.migrations.exceptions.NodeNotFoundError: Migration config_officer.0001_initial dependencies reference nonexistent parent node ('dcim', '0122_standardize_name_length')
```
</details>

<details><summary> 3) Custom fields don't get created </summary>

Either that or the README is misleading.
</details>

After making those changes I was able to get the plugin and netbox back up. I couldn't actually test its functionality yet.

I'd also recommend adding a netbox supported version because I suspect some of the above might be related to earlier versions of netbox. I'm currently testing on 2.9.11

Cheers,

**Comment by artyomovs** [comment]
Hi @jpobeda . Thank you for feedback. 
The reason of the first point - the plugin is compatible only with Netbox >= 2.10 version. It's absolutely my fault that I didn't mention this. I'll do my best to make it compatible with 2.8 and 2.9 versions as well. 
Cusctom fields are not supposed to be created. It's optionally, so I decided to not create them automatically. Probably, I should change this behavior.

Thanks for your comment. I won't close it until I fix these issues.

**Comment by LassePettsson** [comment]
Found issues with upper/lower case on filenames, hostgname and device names in netbox.
ended up with a lot of problem where files could not be found in git because of the upper/lowercase names.
also could not get the SSH connection working. could not find out why.

**Comment by artyomovs** [comment]
Hello @LassePettsson . 
Please check out new version 0.0.3. I fixed the issue with upper/lower case. 
For SSH - did you removed the line _"user: '101'"_ from _docker-compose.yml_ file? To be honest, I don't know how to handle with ssh and this line, so you should comment or delete it.

**Comment by artyomovs** [comment]
I'm working on the 3.x version, will be fixed there.
