### ISSUE TITLE
404 Page not found 

### ISSUE THREAD

**Issue by alexanderdeca** [artyomovs/netbox-plugin-config-officer#3]
Hi,

Thanks for the plugin, similar I gave it a go after watching your YouTube video and  installed it through PyPi. (NetBox version v2.10.3) However getting a "Page not found error" when running the "collect_device_data". 

Not sure where I can look to troubleshoot what might be going wrong.

cheers

Alexander

**Comment by jpobeda** [comment]
@alexanderdeca , I'd start with looking at those custom links you have created. 
They should be pointing to https://yournetbox.com/plugins/config_officer/collect_device_config/{{ obj }}

**Comment by alexanderdeca** [comment]
> @alexanderdeca , I'd start with looking at those custom links you have created.
> They should be pointing to `https://yournetbox.com/plugins/config_officer/collect_device_config/{{ obj }}`

Yeah that is what I am using : 'https://10.255.255.26/plugins/config_officer/collect_device_config/{{ obj }}' and the same goes for the running-config: 'https://10.255.255.26/plugins/config_officer/running_config/{{ obj.name }}'

**Comment by jpobeda** [comment]
@alexanderdeca

Replace 10.255.255.26 on those custom links for the FQDN or whatever you use to normally access your netbox instance.

**Comment by alexanderdeca** [comment]
> @alexanderdeca
> 
> Replace 10.255.255.26 on those custom links for the FQDN or whatever you use to normally access your netbox instance. And close this issue if that resolved it.

10.255.255.26 is my netbox ip

**Comment by artyomovs** [comment]
Hi @alexanderdeca and @jpobeda . Thank you guys. 
@alexanderdeca could you check whether the plugin is installed. (go to Admin -> Admin -> Installed plugins). 
I am creating the manual how to install plugin from pip. Will update readme file soon.

**Comment by alexanderdeca** [comment]
Hi,

The plugin is enabled, from a logging perspective i can see under nginx the
correct request with the correct path.

Thanks

**Comment by alexanderdeca** [comment]
> Hi @alexanderdeca and @jpobeda . Thank you guys.
> @alexanderdeca could you check whether the plugin is installed. (go to Admin -> Admin -> Installed plugins).
> I am creating the manual how to install plugin from pip. Will update readme file soon.

Hi
