### ISSUE TITLE
NameSlugSearchFilterSet Problem

### ISSUE THREAD

**Issue by Sivolen** [artyomovs/netbox-plugin-config-officer#5]
Hi!
After install without docker, i have a problem:
```
<class 'ImportError'>

cannot import name 'NameSlugSearchFilterSet' from 'utilities.filters' (/opt/netbox/netbox/utilities/filters.py)

Python version: 3.8.5
NetBox version: 2.11.3
```
How i may fix it ?

**Comment by boomsfib** [comment]
I'm getting this same error.  Have you been able to resolve?

**Comment by whitejuly07** [comment]
Installation problem

<class 'ImportError'>

cannot import name 'NameSlugSearchFilterSet' from 'utilities.filters' (/opt/netbox/netbox/utilities/filters.py)

Python version: 3.9.2
NetBox version: 3.1.5

**Comment by pcbcid** [comment]
same issue
NetBox version: 3.4.4
Python version: 3.8.10
