### ISSUE TITLE
NetBox v3.0 Support

### ISSUE THREAD

**Issue by ryanmerolle** [artyomovs/netbox-plugin-config-officer#7]
As an FYI here is what changed that could impact or help the plugin:
- HTML Template updates (support change from bootstrap 3 to bootstrap 5)
- Overall UI tweaks
- Custom Queue Support for Plugins netbox-community/netbox/issues/6651

If you find any issues or have any questions feel free to hit us on the slack or add a bug /issue or add to the umbrella UI issue netbox-community/netbox/issues/6797

**Comment by edurguti** [comment]
Does this plugin support netbox 3.0?

**Comment by artyomovs** [comment]
Hi guys. Thank you for your feedback! It doesn't support NetBox 3.0 as for now, but Im working on that.

**Comment by edurguti** [comment]
Thank you for working on this, can we keep this open until you implement support for 3.0? I am looking into building something similar but don't have much time.
