### ISSUE TITLE
Cannot start service netbox-housekeeping

### ISSUE THREAD

**Issue by pslencinas** [artyomovs/netbox-plugin-config-officer#9]
Hi. I can not deploy netbox-plugin config-officer. I received an error trying to create netbox-docker_netbox-housekeeping_1_2da30c. 
Could you help me with this? I'm following step-by-step, from github and youtube.

I'm using Ubuntu: 20.04.3 LTS with vagrant/virtualbox.

Creating netbox-docker_redis_1_eda484f67269       ... done
Creating netbox-docker_postgres_1_d9596c0d647a    ... done
Creating netbox-docker_redis-cache_1_bbd69de6aef9           ... done
Recreating netbox-docker_netbox-housekeeping_1_2da30cc7e86e ... error
Creating netbox-docker_netbox-worker_1_269284fe7c9d         ...

ERROR: for netbox-docker_netbox-housekeeping_1_2da30cc7e86e  Cannot start service netbox-housekeeping: driver failed programming external connectivity on endpoint netbox-docker_netbox-housekeeping_1_2da30cc7e86e (Creating netbox-docker_netbox-worker_1_269284fe7c9d         ... done
Creating netbox-docker_netbox_1_28722ab27218                ... error

ERROR: for netbox-docker_netbox_1_28722ab27218  Cannot start service netbox: driver failed programming external connectivity on endpoint netbox-docker_netbox_1_5cb5c8adec32 (d5516554e621d0452f9d64074071c81e5f64ef273582c0540b1a5c33f535a116): Bind for 0.0.0.0:8080 failed: port is already allocated

**Comment by artyomovs** [comment]
Hello @pslencinas . 
Thank you for the iisue. 
First of all I have to warn you, my plugin is only supported by Netbox 2.7 and earlier. I was out of coding life for a while and didn't have time to fix it. So you could not use it with new NetBox. 
Regarding error - looks strange, but need more investigation. 
Don't you have other containers that listen 8080 port? 

Anyway, my plan is make some changes in my plugin's code and make it available for netbox 3.x.
